version: 2
updates:
  # Enable version updates for GitHub Actions (if any added later)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3

  # Monitor for any npm/node dependencies (if package.json exists)  
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    ignore:
      # Ignore development dependencies
      - dependency-name: "*"
        dependency-type: "development"