# Development Branch Ruleset
# Lighter rules for development branches to encourage collaboration

name: "Development Branch Rules"
description: "Flexible rules for development and feature branches"

target: "branch"
enforcement: "active"
conditions:
  ref_name:
    include:
      - "refs/heads/dev*"
      - "refs/heads/feature/*"
      - "refs/heads/hotfix/*"
      - "refs/heads/bugfix/*"
    exclude:
      - "refs/heads/main"
      - "refs/heads/master"

rules:
  # Allow direct pushes (no PR required)
  - type: "creation"
  
  # Prevent force push to shared dev branches
  - type: "force_push"
    parameters:
      exempt_users: []
      
  # Basic commit message standards
  - type: "commit_message_pattern"
    parameters:
      pattern: ".{10,}"  # At least 10 characters
      operator: "regex"
      negate: false

bypass_actors:
  - actor_id: null
    actor_type: "RepositoryRole" 
    bypass_mode: "always"