# GitHub Repository Ruleset Configuration
# This file documents the recommended ruleset configuration for comfort-control-easehub
# Apply these rules via GitHub UI: Settings → Rules → Rulesets

name: "Main Branch Protection"
description: "Comprehensive protection rules for the main branch and repository"

# Target Configuration
target: "branch"
enforcement: "active"
conditions:
  ref_name:
    include:
      - "refs/heads/main"
      - "refs/heads/master"
    exclude: []

# Branch Protection Rules
rules:
  # Require Pull Requests
  - type: "pull_request"
    parameters:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
      require_last_push_approval: true
      
  # Status Check Requirements
  - type: "required_status_checks"
    parameters:
      strict_branch_policy: true
      required_checks:
        - context: "ci/build"
          integration_id: null
        - context: "security/scan"
          integration_id: null
          
  # Prevent Force Push
  - type: "non_fast_forward"
    
  # Require Linear History
  - type: "required_linear_history"
    
  # Restrict Deletions
  - type: "deletion"
    
  # Restrict Force Push
  - type: "force_push"

# File-based Rules
  # Require approval for sensitive files
  - type: "file_path_restriction"
    parameters:
      restricted_file_paths:
        - "/.github/**"
        - "/SECURITY.md"
        - "/LICENSE"
        - "/package*.json"
        - "/metadata.json"
        - "/*.yml"
        - "/*.yaml"

# Commit Rules
  # Commit signature verification
  - type: "required_signatures"
    
  # Commit message format
  - type: "commit_message_pattern"
    parameters:
      pattern: "^(feat|fix|docs|style|refactor|perf|test|chore|ci|build)(\\(.+\\))?: .{1,50}"
      operator: "regex"
      negate: false

# Metadata Rules
  - type: "tag_name_pattern"
    parameters:
      pattern: "^v\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9]+)*$"
      operator: "regex"
      negate: false

bypass_actors:
  - actor_id: null  # Repository owner
    actor_type: "RepositoryRole"
    bypass_mode: "always"