name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: What happened and what did you expect?
    validations:
      required: true
  - type: input
    attributes:
      label: GNOME Shell version
      placeholder: e.g., 42.9 / 43.8 / 44.5
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: Paste errors from Looking Glass (Alt+F2 → lg) or journalctl -b | grep gnome-shell
      render: text

