name: Feature request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      placeholder: What’s the user need?
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: Describe the solution you’d like
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Mockups, examples, references
