name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Motivation
      description: What problem would this feature solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: Describe the solution you'd like
    validations:
      required: true

